=== Blizzsuxx/XML/saglasnost.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://ftn.uns.ac.rs/saglasnost" xmlns="http://ftn.uns.ac.rs/saglasnost"
    xmlns:ns1="http://ftn.uns.ac.rs/interesovanje"
    xmlns:ns2="http://ftn.uns.ac.rs/potvrda_o_vakcinaciji">
    <xs:import namespace="http://ftn.uns.ac.rs/interesovanje" schemaLocation="interesovanje.xsd"/>
    <xs:import namespace="http://ftn.uns.ac.rs/potvrda_o_vakcinaciji"
        schemaLocation="potvrdaOVakcinaciji.xsd"/>
    <xs:element name="dokument">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="saglasnost_za_sprovodjenje_imunizacije"/>
                <xs:element ref="evidencija_o_vakcinaciji"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="saglasnost_za_sprovodjenje_imunizacije">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="drzavljanstvo">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="republika_srbija">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="jmbg">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:pattern value="[0-9]{13,13}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="stranac">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="naziv_stranog_drzavljanstva"
                                            type="xs:string"/>
                                        <xs:element name="br_pasosa_ili_ebs">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:pattern value="^[0-9]*$"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="osoba" type="TOsoba"/>
                <xs:element name="radni_status">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="zaposlen" type="xs:string" fixed="zaposlen"/>
                            <xs:element name="nezaposlen" type="xs:string" fixed="nezaposlen"/>
                            <xs:element name="penzioner" type="xs:string" fixed="penzioner"/>
                            <xs:element name="ucenik" type="xs:string" fixed="ucenik"/>
                            <xs:element name="student" type="xs:string" fixed="student"/>
                            <xs:element name="dete" type="xs:string" fixed="dete"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="zanimanje">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element fixed="zdravstvena_zastita" name="zdravstvena_zastita"
                                type="xs:string"/>
                            <xs:element fixed="socijalna_zastita" name="socijalna_zastita"
                                type="xs:string"/>
                            <xs:element fixed="prosveta" name="prosveta" type="xs:string"/>
                            <xs:element fixed="mup" name="mup" type="xs:string"/>
                            <xs:element fixed="vojska" name="vojska" type="xs:string"/>
                            <xs:element fixed="drugo" name="drugo" type="xs:string"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="korisnik_ustanove_soc_zastite" type="ns1:TIzbor"/>
                <xs:element name="izjava">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="saglasnost" type="ns1:TIzbor"/>
                            <xs:element name="vakcina" type="ns2:TVakcina"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="potpis" type="xs:string"/>
                <xs:element name="datum" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="evidencija_o_vakcinaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="zdravstvena_ustanova" type="xs:string"/>
                <xs:element name="vakcinacijski_punkt" type="xs:string"/>
                <xs:element name="ime_prezime_faksimil_brtel">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ime" type="xs:string"/>
                            <xs:element name="prezime" type="xs:string"/>
                            <xs:element name="faksimil">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="brtel">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]{10,10}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tabela">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="element">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="1" name="vakcina" type="ns2:TVakcina"/>
                                        <xs:element name="datum_davanja" type="xs:date"/>
                                        <xs:element fixed="IM" name="nacin_davanja" type="xs:string"/>
                                        <xs:element name="ekstremitet">
                                            <xs:complexType>
                                                <xs:choice>
                                                  <xs:element fixed="LR" name="dr" type="xs:string"/>
                                                  <xs:element fixed="DR" name="lv" type="xs:string"
                                                  />
                                                </xs:choice>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="serija" type="xs:long"/>
                                        <xs:element name="proizvodjac" type="ns2:TVakcina"/>
                                        <xs:element name="nezeljena_reakcija" type="xs:boolean"/>
                                        <xs:element name="potpis_lekara" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="privremene_kontradikcije">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="datum" type="xs:date"/>
                                        <xs:element name="dijagnoza" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="trajne_kontradikcije" type="ns1:TIzbor"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TOsoba">
        <xs:sequence>
            <xs:element name="ime" type="xs:string"/>
            <xs:element name="prezime" type="xs:string"/>
            <xs:element name="ime_roditelja" type="xs:string"/>
            <xs:element name="pol" type="ns2:TPol"/>
            <xs:element name="datum_rodjenja" type="xs:date"/>
            <xs:element name="mesto_rodjenja" type="xs:string"/>
            <xs:element name="adresa">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="^[a-zA-Z]+[a-zA-Z0-9]*$"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="mobilni">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="06[0-9]{8,8}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="fiksni">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="01[0-9]{7,7}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="e-adresa">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="/^[^\s@]+@[^\s@]+\.[^\s@]+$/"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Blizzsuxx/XML/demo/src/main/resources/schemas/saglasnost1.xml
<?xml version="1.0" encoding="UTF-8"?>
<sa:dokument xmlns:ns1="http://ftn.uns.ac.rs/interesovanje"
 xmlns:ns2="http://ftn.uns.ac.rs/potvrda_o_vakcinaciji"
 xmlns:sa="http://ftn.uns.ac.rs/saglasnost"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/saglasnost file:/media/user/games/Projects/XML/demo/src/main/resources/schemas/saglasnost.xsd">
    <sa:saglasnost_za_sprovodjenje_imunizacije>
        <sa:drzavljanstvo>
            <sa:republika_srbija>
                <sa:jmbg>0000000000000</sa:jmbg>
            </sa:republika_srbija>
        </sa:drzavljanstvo>
        <sa:osoba>
            <sa:ime>ime0</sa:ime>
            <sa:prezime>prezime0</sa:prezime>
            <sa:ime_roditelja>ime_roditelja0</sa:ime_roditelja>
            <sa:pol>
                <sa:Musko>Musko</sa:Musko>
            </sa:pol>
            <sa:datum_rodjenja>2006-05-04</sa:datum_rodjenja>
            <sa:mesto_rodjenja>mesto_rodjenja0</sa:mesto_rodjenja>
            <sa:adresa>^A$</sa:adresa>
            <sa:mesto>mesto0</sa:mesto>
            <sa:mobilni>0600000000</sa:mobilni>
            <sa:fiksni>010000000</sa:fiksni>
            <sa:e-adresa>/^!@!.!$/</sa:e-adresa>
        </sa:osoba>
        <sa:radni_status>
            <sa:student>student</sa:student>
        </sa:radni_status>
        <sa:zanimanje>
            <sa:drugo>drugo</sa:drugo>
        </sa:zanimanje>
        <sa:korisnik_ustanove_soc_zastite izabran="false"/>
        <sa:izjava>
            <sa:saglasnost izabran="false"/>
            <sa:vakcina>
                <sa:Sinopharm>Sinopharm</sa:Sinopharm>
            </sa:vakcina>
        </sa:izjava>
        <sa:potpis>potpis0</sa:potpis>
        <sa:datum>2006-05-04</sa:datum>
    </sa:saglasnost_za_sprovodjenje_imunizacije>
    <sa:evidencija_o_vakcinaciji>
        <sa:zdravstvena_ustanova>zdravstvena_ustanova0</sa:zdravstvena_ustanova>
        <sa:vakcinacijski_punkt>vakcinacijski_punkt0</sa:vakcinacijski_punkt>
        <sa:ime_prezime_faksimil_brtel>
            <sa:ime>ime1</sa:ime>
            <sa:prezime>prezime1</sa:prezime>
            <sa:faksimil>0</sa:faksimil>
            <sa:brtel>0000000000</sa:brtel>
        </sa:ime_prezime_faksimil_brtel>
        <sa:tabela>
            <sa:element>
                <sa:vakcina>
                    <sa:Pfizer>Pfizer</sa:Pfizer>
                </sa:vakcina>
                <sa:datum_davanja>2006-05-04</sa:datum_davanja>
                <sa:nacin_davanja>IM</sa:nacin_davanja>
                <sa:ekstremitet>
                    <sa:lv>DR</sa:lv>
                </sa:ekstremitet>
                <sa:serija>-1073741773</sa:serija>
                <sa:proizvodjac>
                    <sa:Sinopharm>Sinopharm</sa:Sinopharm>
                </sa:proizvodjac>
                <sa:nezeljena_reakcija>false</sa:nezeljena_reakcija>
                <sa:potpis_lekara>potpis_lekara0</sa:potpis_lekara>
            </sa:element>
            <sa:element>
                <sa:vakcina>
                    <sa:Sputnik>Sputnik</sa:Sputnik>
                </sa:vakcina>
                <sa:datum_davanja>2006-05-04</sa:datum_davanja>
                <sa:nacin_davanja>IM</sa:nacin_davanja>
                <sa:ekstremitet>
                    <sa:lv>DR</sa:lv>
                </sa:ekstremitet>
                <sa:serija>-1073741773</sa:serija>
                <sa:proizvodjac>
                    <sa:Sinopharm>Sinopharm</sa:Sinopharm>
                </sa:proizvodjac>
                <sa:nezeljena_reakcija>false</sa:nezeljena_reakcija>
                <sa:potpis_lekara>potpis_lekara1</sa:potpis_lekara>
            </sa:element>
            <sa:privremene_kontradikcije>
                <sa:datum>2006-05-04</sa:datum>
                <sa:dijagnoza>dijagnoza0</sa:dijagnoza>
            </sa:privremene_kontradikcije>
            <sa:trajne_kontradikcije izabran="false"/>
        </sa:tabela>
    </sa:evidencija_o_vakcinaciji>
</sa:dokument>
