=== Blizzsuxx/XML/XML Seme/izvestaj_o_imunizaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http:/www.ftn.uns.ac.rs/izvestaj_o_imunizaciji"
    xmlns:imunizacija="http:/www.ftn.uns.ac.rs/izvestaj_o_imunizaciji"
    xmlns:ns1="http://ftn.uns.ac.rs/potvrda_o_vakcinaciji"
    xmlns:ns2="https://ftn.uns.ac.rs/potvrda_o_vakcinaciji">
    <xs:import namespace="https://ftn.uns.ac.rs/potvrda_o_vakcinaciji"
        schemaLocation="potvrdaOVakcinaciji.xsd"/>
    <xs:element name="izvestaj_o_imunizaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="izvestaj_se_odnosi_na">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="datum_od" type="xs:date"/>
                            <xs:element name="datum_do" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="podaci">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="imunizacija">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="podneto" type="xs:long"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="zeleni_sertifikat">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="podneto" type="xs:long"/>
                                        <xs:element name="primljeno" type="xs:long"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dato_je_vakcina" type="xs:long"/>
                <xs:element name="primljene_doze">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="doza" type="imunizacija:TDoza"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="proizvodjaci">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="proizvodjac"
                                type="imunizacija:TProizvodjac"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datum_izdavanja" type="xs:date"/>
                <xs:element name="potpis" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TProizvodjac">
        <xs:sequence>
            <xs:element name="Ime" type="ns2:TVakcina"/>
            <xs:element name="broj_doza" type="xs:long"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TDoza">
        <xs:sequence>
            <xs:element name="redni_broj_doze" type="xs:long"/>
            <xs:element name="primljena_kolicina" type="xs:long"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Blizzsuxx/XML/XML Seme/izvestaj_o_imunizaciji1.xml
<?xml version="1.0" encoding="UTF-8"?>
<imunizacija:izvestaj_o_imunizaciji xmlns:imunizacija="http:/www.ftn.uns.ac.rs/izvestaj_o_imunizaciji"
 xmlns:ns1="http://ftn.uns.ac.rs/potvrda_o_vakcinaciji"
 xmlns:ns2="https://ftn.uns.ac.rs/potvrda_o_vakcinaciji"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http:/www.ftn.uns.ac.rs/izvestaj_o_imunizaciji file:/media/user/games/Projects/XML/XML%20Seme/izvestaj_o_imunizaciji.xsd">
    <imunizacija:izvestaj_se_odnosi_na>
        <imunizacija:datum_od>2006-05-04</imunizacija:datum_od>
        <imunizacija:datum_do>2006-05-04</imunizacija:datum_do>
    </imunizacija:izvestaj_se_odnosi_na>
    <imunizacija:podaci>
        <imunizacija:imunizacija>
            <imunizacija:podneto>-1073741773</imunizacija:podneto>
        </imunizacija:imunizacija>
        <imunizacija:zeleni_sertifikat>
            <imunizacija:podneto>-1073741773</imunizacija:podneto>
            <imunizacija:primljeno>-1073741773</imunizacija:primljeno>
        </imunizacija:zeleni_sertifikat>
    </imunizacija:podaci>
    <imunizacija:dato_je_vakcina>-1073741773</imunizacija:dato_je_vakcina>
    <imunizacija:primljene_doze>
        <imunizacija:doza>
            <imunizacija:redni_broj_doze>-1073741773</imunizacija:redni_broj_doze>
            <imunizacija:primljena_kolicina>-1073741773</imunizacija:primljena_kolicina>
        </imunizacija:doza>
        <imunizacija:doza>
            <imunizacija:redni_broj_doze>-1073741773</imunizacija:redni_broj_doze>
            <imunizacija:primljena_kolicina>-1073741773</imunizacija:primljena_kolicina>
        </imunizacija:doza>
    </imunizacija:primljene_doze>
    <imunizacija:proizvodjaci>
        <imunizacija:proizvodjac>
            <imunizacija:Ime>
                <ns2:Moderna>Moderna</ns2:Moderna>
            </imunizacija:Ime>
            <imunizacija:broj_doza>-1073741773</imunizacija:broj_doza>
        </imunizacija:proizvodjac>
        <imunizacija:proizvodjac>
            <imunizacija:Ime>
                <ns2:Sinopharm>Sinopharm</ns2:Sinopharm>
            </imunizacija:Ime>
            <imunizacija:broj_doza>-1073741773</imunizacija:broj_doza>
        </imunizacija:proizvodjac>
    </imunizacija:proizvodjaci>
    <imunizacija:datum_izdavanja>2006-05-04</imunizacija:datum_izdavanja>
    <imunizacija:potpis>potpis0</imunizacija:potpis>
</imunizacija:izvestaj_o_imunizaciji>
