=== Blizzsuxx/XML/XML Seme/zahtevZaSertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://ftn.uns.ac.rs/zahtev_za_sertifikat"
    xmlns="http://ftn.uns.ac.rs/zahtev_za_sertifikat">

    <xs:element name="zahtevZaSertifikat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Pacijent" type="TOsoba"/>
                <xs:element name="razlog">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="5"/>
                            <xs:whiteSpace value="preserve"/>
                            <xs:pattern value="[A-Z][a-z]{2,200}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="mesto">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Z][a-z]{2,15}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="dan">
                    <xs:simpleType>
                        <xs:restriction base="xs:gDay"> </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="mesec" type="xs:gMonth"/>
                <xs:element name="godina">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:pattern value="[0-9]{1,1}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="potpis">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[a-z]{2,15}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TOsoba">
        <xs:sequence>
            <xs:element name="ime">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]{2,15}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="prezime">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]{2,20}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="datum" type="xs:date"/>
            <xs:element name="pol" type="TPol"> </xs:element>
            <xs:element name="jmbg">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{13,13}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="pasos">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{10,10}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPol">
        <xs:choice>
            <xs:element fixed="Musko" name="Musko" type="xs:string"/>
            <xs:element fixed="Zensko" name="Zensko" type="xs:string"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== Blizzsuxx/XML/XML Seme/zahtevZaSertifikatGenerisani1.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtevZaSertifikat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/Uros/Desktop/zahtevZaSertifikat.xsd">
    <Pacijent>
        <ime>Vbhyrpdjmnctddux</ime>
        <prezime>Kgbdkv</prezime>
        <datum>2023-04-03</datum>
        <pol>
            <Zensko>Zensko</Zensko>
        </pol>
        <jmbg>2901324244624</jmbg>
        <pasos>6981439060</pasos>
    </Pacijent>
    <razlog>Qiqpqcdsomcinzyjdcshnahghweeuowjgykqgbgeemzzxheqjxticqavyoohfiomwsnsbrrqeerqczyiwdzxlewtplflwphpyqb</razlog>
    <mesto>Eoigbsnwvc</mesto>
    <dan>---18</dan>
    <mesec>--06</mesec>
    <godina>7</godina>
    <potpis>dpfpqtxkdmvpxhk</potpis>
</zahtevZaSertifikat>
