=== Blizzsuxx/XML/demo/src/main/resources/schemas/interesovanje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://ftn.uns.ac.rs/interesovanje" xmlns="http://ftn.uns.ac.rs/interesovanje"
    xmlns:ns1="http://ftn.uns.ac.rs/potvrda_o_vakcinaciji">
    <xs:element name="interesovanje_za_vakcinisanje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="drzavljanstvo">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="drzavljanstvo_republike_srbije" type="xs:string"/>
                            <xs:element name="strani_sa_broravkom" type="xs:string"/>
                            <xs:element name="strani_bez_boravka" type="xs:string"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="osoba" type="TOsoba"/>
                <xs:element name="lokacija" type="xs:string"/>
                <xs:element name="vakcine">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="izabrane_vakcine">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="TIzbor">
                                            <xs:sequence>
                                                <xs:element minOccurs="0" name="vakcina" type="TVakcina"/>
                                            </xs:sequence>
                                        </xs:extension>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="bilo_sta" type="TIzbor"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="davalac_krvi" type="TIzbor"/>
                <xs:element name="dan" type="xs:gMonthDay"/>
                <xs:element name="godina">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{1}"/>
                    </xs:restriction>
                </xs:simpleType>
                </xs:element>
                <xs:element name="potpis" type="xs:string"/>
                <xs:element name="nadjenTermin" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TVakcina">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="1" name="Pfizer" fixed="Pfizer" type="xs:string"/>
            <xs:element minOccurs="0" maxOccurs="1" name="Sinopharm" fixed="Sinopharm" type="xs:string"/>
            <xs:element minOccurs="0" maxOccurs="1" name="Moderna" fixed="Moderna" type="xs:string"/>
            <xs:element minOccurs="0" maxOccurs="1" name="Sputnik" fixed="Sputnik" type="xs:string"/>
            <xs:element minOccurs="0" maxOccurs="1" fixed="AstraZeneca" name="AstraZeneca" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TOsoba">
        <xs:sequence>
            <xs:element name="jmbg">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{13,13}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="ime" type="xs:string"/>
            <xs:element name="prezime" type="xs:string"/>
            <xs:element name="e-adresa">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="mobilni">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{10,10}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="fiksni">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{9}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TIzbor">
        <xs:attribute name="izabran" type="xs:boolean" use="required"/>
    </xs:complexType>
    <xs:complexType name="TZdravstvenaUstanova">
        <xs:sequence>
            <xs:element name="naziv">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]{5,30}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="ulica">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]{2,30}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{1,3}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="grad">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]{2,20}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPol">
        <xs:choice>
            <xs:element fixed="Musko" name="Musko" type="xs:string"/>
            <xs:element fixed="Zensko" name="Zensko" type="xs:string"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== Blizzsuxx/XML/demo/src/main/resources/schemas/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<in:interesovanje_za_vakcinisanje xmlns:ns1="http://ftn.uns.ac.rs/potvrda_o_vakcinaciji"
 xmlns:in="http://ftn.uns.ac.rs/interesovanje"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/interesovanje file:/media/user/games/Projects/XML/demo/src/main/resources/schemas/interesovanje.xsd">
    <in:drzavljanstvo>
        <in:drzavljanstvo_republike_srbije>drzavljanstvo_republike_srbije0</in:drzavljanstvo_republike_srbije>
    </in:drzavljanstvo>
    <in:osoba>
        <in:jmbg>0000000000000</in:jmbg>
        <in:ime>ime0</in:ime>
        <in:prezime>prezime0</in:prezime>
        <in:e-adresa>/^!@!.!$/</in:e-adresa>
        <in:mobilni>0600000000</in:mobilni>
        <in:fiksni>010000000</in:fiksni>
    </in:osoba>
    <in:lokacija>lokacija0</in:lokacija>
    <in:vakcine>
        <in:izabrane_vakcine izabran="false">
            <in:vakcina>
                <in:Sinopharm>Sinopharm</in:Sinopharm>
            </in:vakcina>
        </in:izabrane_vakcine>
        <in:bilo_sta izabran="false"/>
    </in:vakcine>
    <in:davalac_krvi izabran="false"/>
    <in:dan>--12-30</in:dan>
    <in:potpis>potpis0</in:potpis>
</in:interesovanje_za_vakcinisanje>
