=== Blizzsuxx/XML/demo/src/main/resources/schemas/potvrdaOVakcinaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://ftn.uns.ac.rs/potvrda_o_vakcinaciji" xmlns="http://ftn.uns.ac.rs/potvrda_o_vakcinaciji">

    <xs:element name="potvrdaOVakcinaciji">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sifra" type="xs:string"/>
                <xs:element name="Pacijent" type="TOsoba"/>
                <xs:element name="datumPrva" type="xs:date"/>
                <xs:element name="serija">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]{8,8}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="datumDruga" type="xs:date"/>
                <xs:element name="ustanova" type="TZdravstvenaUstanova"/>
                <xs:element minOccurs="1" name="vakcina" type="TVakcina"/>
                <xs:element name="datumPotvrde" type="xs:date"/>
                <xs:element name="QRCode">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="4296"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TOsoba">
        <xs:sequence>
            <xs:element name="ime">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]{2,15}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="prezime">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]{2,20}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="datum" type="xs:date"/>
            <xs:element name="pol" type="TPol"> </xs:element>
            <xs:element name="jmbg">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{13,13}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TZdravstvenaUstanova">
        <xs:sequence>
            <xs:element name="naziv">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]{5,30}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="ulica">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]{2,30}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{1,3}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="grad">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]{2,20}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPol">
        <xs:choice>
            <xs:element fixed="Musko" name="Musko" type="xs:string"/>
            <xs:element fixed="Zensko" name="Zensko" type="xs:string"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="TVakcina">
        <xs:choice>
            <xs:element name="Pfizer" fixed="Pfizer" type="xs:string"/>
            <xs:element name="Sinopharm" fixed="Sinopharm" type="xs:string"/>
            <xs:element name="Moderna" fixed="Moderna" type="xs:string"/>
            <xs:element name="Sputnik" fixed="Sputnik" type="xs:string"/>
            <xs:element fixed="AstraZeneca" name="AstraZeneca" type="xs:string"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== Blizzsuxx/XML/XML Seme/potvrdaOVakcinacijiGenerisana1.xml
<?xml version="1.0" encoding="UTF-8"?>
<potvrdaOVakcinaciji xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/Uros/Desktop/potvrdaOVakcinaciji.xsd">
    <Pacijent>
        <ime>Eozbarurp</ime>
        <prezime>Ulkrosncjstrp</prezime>
        <datum>2023-06-27Z</datum>
        <pol>
            <Musko>Musko</Musko>
        </pol>
        <jmbg>7019496909562</jmbg>
    </Pacijent>
    <datumPrva>2021-12-25Z</datumPrva>
    <serija>55593906</serija>
    <datumDruga>2023-03-24Z</datumDruga>
    <ustanova>
        <naziv>Fzgzaqojqtdtfch</naziv>
        <ulica>Xyvysgncpebwszyeeaephghqsq</ulica>
        <broj>9</broj>
        <grad>Huhlypuxwppwlidhxe</grad>
    </ustanova>
    <vakcina>
        <Pfizer>Pfizer</Pfizer>
    </vakcina>
    <datumPotvrde>2022-08-16</datumPotvrde>
    <QRCode>Zmi-yz6CDTRop:IfQ7LvopO7gq4y7:Khb:5Qk4cS_vLVj0w25bi-d2UAuXdRmBR:m:awaL5AkYLTxvMiAuqCFg_5AxpNpgtMmdUY-u7so.40mblRoReALOrT6f4yG9uhd7rOmZ6EqUf-OGhcPShGIlZAyIw7jKOmG_aD7SLWTVf1MgktHEu3OThorLZsLcQ0e.fyM5Um_UktI0UwfiMieWsEConeB8WLiwulO:R7OG.4ovFc1-EW1c9n-Rgr:nP3Y_qUX5R0bBK21RDFjVaR7FC73hPQQ1fWi3n7xeQ_JONS8Qs4BRonDDAki-cBW-X7iRXBJMwQ0:KT3uKzSnFAs-ejdkZ6mzs7a4qbHLh22GN2QEKpjo6Dgi.GNHgCrTkf5f1lUjDWQz0xarn56EDuDjD_-0YwZ4hMvZnpgp:WnsbCt02EArzxQnRus96lmm1X5ftnu2mVQ.toz32o6DADbCkS3N29Ca8P1S-lmBzl3IeZegyAB9GVuAK-QzHobCO0iR-smVwl:.XKDyIKdnq:wx0JXTRbvO9A0lYTORJ3aI5ia:0.yzQ6xk19jKe4viiQNgNZrmx5xBwenxgccC.sSkuXoaac1VQPx2PA1ZygZkRHWTxpYmUFUOXEDn2wf:ZcyuZ5llvryq01uJTPtSs0VINB3XCO_q7bttv_sdl1AB2G2Cqj.xoZVnwxlIVyd8szHsgxLPZg-29flgsfgMM_aCSNtsHpoHdvNfEXrOG9T9h8j4Ns-bT8:JF8T.EZD.Z3tp20lPLZ3wyePaNIJLJa_P6hIaQxqD1CYMJydjc7p2-YUvYmfmxbAzpEkMa:mWRsi_IZIZWFL8r1ZhMkZmBLSazw0LA8DM37RuzXoYw.8r9aNyqTw_GxluSjUtRi5_Tp-TknOdvhMvpBn_RgfaTcf7UIlLcUadTNskug2Xg8QKXDzhXVOkIOw0g7.cl70Zjf:wiWFq4STTva-gbgbLe4-PDOAh:PosfZbXC2eywfw3RLQGyHQVh-YqCMC38MkCIcchSwBsft_D:xgjCn8EVkyMTF2Qsz9CY5pFprdlmNmj1FZSkcwlOGDsOHaIY0CrP2DSj4:YrW1weoAWhCwip7DqZEO8XWNvtbVw:-RkDdfm.n-kF:5h-ToqSd5bKkIwYqkqRAhd:_RD0e5-jXyQwWyTc5KqigN9dInOoA2P5DPq</QRCode>
</potvrdaOVakcinaciji>

=== Blizzsuxx/XML/XML Seme/potvrda_o_vakcinaciji1.xml
<?xml version="1.0" encoding="UTF-8"?>
<potvrdaOVakcinaciji xmlns="https://ftn.uns.ac.rs/potvrda_o_vakcinaciji"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://ftn.uns.ac.rs/potvrda_o_vakcinaciji file:/media/user/games/Projects/XML/XML%20Seme/potvrdaOVakcinaciji.xsd">
    <Pacijent>
        <ime>Aaa</ime>
        <prezime>Aaa</prezime>
        <datum>2006-05-04</datum>
        <pol>
            <Musko>Musko</Musko>
        </pol>
        <jmbg>0000000000000</jmbg>
    </Pacijent>
    <datumPrva>2006-05-04</datumPrva>
    <serija>00000000</serija>
    <datumDruga>2006-05-04</datumDruga>
    <ustanova>
        <naziv>Aaaaaa</naziv>
        <ulica>Aaa</ulica>
        <broj>0</broj>
        <grad>Aaa</grad>
    </ustanova>
    <vakcina>
        <Sputnik>Sputnik</Sputnik>
    </vakcina>
    <datumPotvrde>2006-05-04</datumPotvrde>
    <QRCode>QRCode0</QRCode>
</potvrdaOVakcinaciji>

=== Blizzsuxx/XML/demo/src/main/resources/schemas/potvrdaOVakcinaciji1.xml
<?xml version="1.0" encoding="UTF-8"?>
<potvrdaOVakcinaciji xmlns="http://ftn.uns.ac.rs/potvrda_o_vakcinaciji"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/potvrda_o_vakcinaciji file:/media/user/games/Projects/XML/demo/src/main/resources/schemas/potvrdaOVakcinaciji.xsd">
    <Pacijent>
        <ime>Aaa</ime>
        <prezime>Aaa</prezime>
        <datum>2006-05-04</datum>
        <pol>
            <Zensko>Zensko</Zensko>
        </pol>
        <jmbg>0000000000000</jmbg>
    </Pacijent>
    <datumPrva>2006-05-04</datumPrva>
    <serija>00000000</serija>
    <datumDruga>2006-05-04</datumDruga>
    <ustanova>
        <naziv>Aaaaaa</naziv>
        <ulica>Aaa</ulica>
        <broj>0</broj>
        <grad>Aaa</grad>
    </ustanova>
    <vakcina>
        <Sinopharm>Sinopharm</Sinopharm>
    </vakcina>
    <datumPotvrde>2006-05-04</datumPotvrde>
    <QRCode>QRCode0</QRCode>
</potvrdaOVakcinaciji>
